# frozen_string_literal: true

# constants used for fixed field error checking
module MarcCleanup
  GOV_PUB = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/gov_pub.yml")
  LANGUAGE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/language_codes.yml")
  PLACE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/place_codes.yml")
  RECORD_TYPES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/record_types.yml")
  AUDIENCE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/audience_codes.yml")
  ITEM_FORM_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/item_form_codes.yml")
  BOOK_CONTENTS = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/book_contents.yml")
  BOOK_ILLUSTRATION = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/book_illustration.yml")
  BOOK_LIT_FORM = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/book_lit_form.yml")
  BOOK_BIOGRAPHY = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/book_biography.yml")
  COMPUTER_FILE_TYPE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/computer_file_type.yml")
  MAP_PROJECTION = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/map_projection.yml")
  MAP_RELIEF = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/map_relief.yml")
  MAP_TYPE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/map_type.yml")
  MAP_SPECIAL_FORMAT = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/map_special_format.yml")
  MUSIC_ACCOMPANY = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_accompany.yml")
  MUSIC_COMPOSITION = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_composition.yml")
  MUSIC_FORMAT = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_format.yml")
  MUSIC_LITERARY_TEXT = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_literary_text.yml")
  MUSIC_PART = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_part.yml")
  MUSIC_TRANSPOSITION = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/music_transposition.yml")
  CR_CONTENTS = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_contents.yml")
  CR_FREQUENCY = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_frequency.yml")
  CR_REGULARITY = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_regularity.yml")
  CR_ORIGINAL_FORM = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_original_form.yml")
  CR_ORIGINAL_SCRIPT = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_original_script.yml")
  CR_TYPE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_type.yml")
  CR_WORK_NATURE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/cr_work_nature.yml")
  VISUAL_TECHNIQUE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/visual_technique.yml")
  VISUAL_TYPE = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/f008/visual_type.yml")
end
