# frozen_string_literal: true

# constants used for fixed field error checking
module MarcCleanup
  GOV_PUB_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/gov_pub_codes.yml")
  LANGUAGE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/language_codes.yml")
  PLACE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/place_codes.yml")
  RECORD_TYPES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/record_types.yml")
  REMOTE_DATA_TYPES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/remote_data_types.yml")
  AUDIENCE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/audience_codes.yml")
  ITEM_FORM_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/item_form_codes.yml")
  BOOK_CONTENTS_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/book_contents_codes.yml")
  BOOK_ILLUSTRATION_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/book_illustration_codes.yml")
  BOOK_LIT_FORM_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/book_lit_form_codes.yml")
  BOOK_BIOGRAPHY_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/book_biography_codes.yml")
  COMPUTER_FILE_TYPE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/computer_file_type_codes.yml")
  MAP_PROJECTION_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/map_projection_codes.yml")
  MAP_RELIEF_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/map_relief_codes.yml")
  MAP_TYPE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/map_type_codes.yml")
  MAP_SPECIAL_FORMAT_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/map_special_format_codes.yml")
  MUSIC_ACCOMPANY_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_accompany_codes.yml")
  MUSIC_COMPOSITION_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_composition_codes.yml")
  MUSIC_FORMAT_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_format_codes.yml")
  MUSIC_LITERARY_TEXT_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_literary_text_codes.yml")
  MUSIC_PART_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_part_codes.yml")
  MUSIC_TRANSPOSITION_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/music_transposition_codes.yml")
  CR_CONTENTS_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_contents_codes.yml")
  CR_FREQUENCY_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_frequency_codes.yml")
  CR_REGULARITY_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_regularity_codes.yml")
  CR_ORIGINAL_FORM_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_original_form_codes.yml")
  CR_ORIGINAL_SCRIPT_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_original_script_codes.yml")
  CR_TYPE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_type_codes.yml")
  CR_WORK_NATURE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/cr_work_nature_codes.yml")
  VISUAL_TECHNIQUE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/visual_technique_codes.yml")
  VISUAL_TYPE_CODES = YAML.load_file("#{ROOT_DIR}/yaml/fixed_fields/visual_type_codes.yml")
end
